### ISSUE TITLE
`Assignee` is always empty

### ISSUE THREAD

**Issue by ymtdzzz** [ymtdzzz/issue-scouter#11]
```yml
repositories:
  groupA:
    - https://github.com/ymtdzzz/issue-scouter
```

![Image](https://github.com/user-attachments/assets/c19166d0-9b07-4e1e-acd5-1aae52ec338e)
